#!/bin/bash
#
# Copyright (C) 2011 Christoph Lehner, Nathan Goldschmidt
#
#    v1[Lehner]:      Original version
#    v2[Goldschmidt]: Use ghostscript to remove invisible content, format FN
#    v3[Lehner]:      Streamline code
#
# All programs in this directory and subdirectories are published under the GNU
# General Public License as described below.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA
#
# Further information about the GNU GPL is available at:
# http://www.gnu.org/copyleft/gpl.ja.html

#
# Assign arguments
#
fn=$1
fnout=$2
page=$3
left=$4
top=$5
right=$6
bottom=$7

#
# Create temporary directory
#
tdir=$(mktemp -d)
mkdir -p $tdir

#
# Use a simple filename for LaTeX with .pdf extension
#
cp -f $fn $tdir/i.pdf

#
# Use LaTeX to extract the
#
cat > $tdir/o.tex <<EOF
\documentclass{article}
\usepackage[left=0cm,right=0cm,bottom=0cm,top=0cm]{geometry}
\usepackage{graphicx}
\begin{document}
\includegraphics[page=$page,trim=$left $bottom $right $top,clip]{$tdir/i.pdf}
\end{document}
EOF

pdflatex -output-directory=$tdir $tdir/o.tex
pdfcrop $tdir/o.pdf

#
# Use ghostscript to remove invisible content
#
gs -q -sDEVICE=pdfwrite -dNOPAUSE -dBATCH \
    -sOutputFile=$fnout                   \
    -f $tdir/o-crop.pdf

rm -rf $tdir
